import React, { useState, useEffect } from 'react'
import { Loader, Card, FormField } from "../components"

const RenderCards = ({data, title}) => {
  if(data?.length > 0) {
    return data.map((post) => <Card key={post.id} {...post}/>)
  }

  return (
    <h2 className="mt-5 font-medium text-purple-500 ">{title}</h2>
  )


} 
const Home = () => {

  const [loading, setLoading] = useState(false);
  const [allPost, setAllPost ] = useState(null);

  const [searchText, setSearchText] = useState('')

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-transparent bg-clip-text bg-gradient-to-r  from-violet-500 via-purple-500 to-pink-500 background-animate text-[32px]">
          The Imagination Collection
        </h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[600px]">
          Browse through people imagination collection with stuning visual generated by DALL-E 
        </p>
      </div>

      <div className="mt-10">
        <FormField />
      </div>

      <div className="mt-10">
        {loading ?(
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ): (
          <>
            {searchText && (
              <h2 className="font-medium text-[#222328]">
                Showing result for "<span className="text-[#222328] font-bold">{searchText}</span>"
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={[]}
                  title="No Result Found"
                />
              ) : (
                <RenderCards
                  data={[]}
                  title="No Posts Found"
                />
              )}
            </div>
          </>
        )} 
      </div>
    </section>
  )
}

export default Home